version: '1'
services:
    db:
        build:
            context: ./
            dockerfile: ./docker/db/Dockerfile
            environment:
                - MONGO_DATA_DIR=/data/db
                - MONGO_LOG_DIR=/dev/null
                expose:
                    - 27017

                    api:
                        build:
                            context: ./
                            dockerfile: ./docker/api/Dockerfile
                            environment:
                                - NODE_ENV=dev
                                - DB_HOST=db
                                volumes:
                                    - ./src:/home/node/app/src
                                    ports:
                                        - 9000:9000
                                        links:
                                            - db
                                            depends_on:
                                                - db
